# Generated by Django 4.1 on 2022-08-06 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_category_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('event_price',), 'verbose_name': 'События', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='dish',
            name='position',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
