# Generated by Django 4.1 on 2022-08-06 13:06

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('exactly_about_us', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Про нас',
                'verbose_name_plural': 'Про нас',
            },
        ),
        migrations.CreateModel(
            name='Specials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('about', models.TextField(max_length=2000)),
                ('picture', models.ImageField(upload_to=base.models.Specials.get_date_name)),
            ],
            options={
                'verbose_name': 'Cпециальные предложения',
                'verbose_name_plural': 'Cпециальные предложения',
            },
        ),
        migrations.RemoveField(
            model_name='dish',
            name='special',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=2000, unique=True),
        ),
    ]
