# Generated by Django 4.1 on 2022-08-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_aboutus_specials_remove_dish_special_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='pozition',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
