# Generated by Django 4.1 on 2022-08-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_aboutus_pozition'),
    ]

    operations = [
        migrations.AddField(
            model_name='specials',
            name='title',
            field=models.TextField(default='no title', max_length=500),
            preserve_default=False,
        ),
    ]
