# Generated by Django 4.1 on 2022-08-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_galery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery',
            name='title',
        ),
    ]
