# Generated by Django 4.1 on 2022-08-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_galery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='pozition',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
