# Generated by Django 4.1 on 2022-08-09 20:42

import base.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_galery_pozition'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('preview', models.ImageField(upload_to=base.models.VideoAboutUs.get_date_name)),
                ('video_link', models.FilePathField()),
            ],
            options={
                'verbose_name': 'Обзорное видео',
                'verbose_name_plural': 'Обзорное видео',
            },
        ),
    ]
