# Generated by Django 4.1 on 2022-08-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_videoaboutus_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoaboutus',
            name='video_link',
            field=models.CharField(max_length=200),
        ),
    ]
