# Generated by Django 4.1 on 2022-08-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_videoaboutus_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoaboutus',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
