# Generated by Django 4.1 on 2022-08-09 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_videoaboutus_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('mail', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Invalid mail', regex='^[^-|_]\\w*[-{0,1}]?\\w*?[@]?\\w*(.com)?$')])),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Invalid phone', regex='^\\d{8,11}$')])),
                ('date', models.DateField(max_length=30, validators=[django.core.validators.RegexValidator(message='Invalid date', regex='^(\\d{1,2})([-: ]\\d{1,2})?$')])),
                ('time', models.TimeField(max_length=30, validators=[django.core.validators.RegexValidator(message='Invalid time', regex='^(\\d{1,2})([-: ]\\d{1,2})?$')])),
                ('number_of_people', models.PositiveIntegerField(max_length=2, validators=[django.core.validators.RegexValidator(message='Invalid time', regex='^\\^[1-5][1-9]$$')])),
                ('text', models.TextField(blank=True, max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date', '-is_processed'),
            },
        ),
        migrations.AlterField(
            model_name='videoaboutus',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
