# Generated by Django 4.1 on 2022-08-10 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_reservationform_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationform',
            name='date',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid date', regex='^(\\d{1,2})([-: .]\\d{1,2})?(-\\d{4})?$')]),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='time',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid time', regex='^(\\d{1,2})([-: ]\\d{1,2})?$')]),
        ),
    ]
