# Generated by Django 4.1 on 2022-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_reservationform_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationform',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='mail',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='number_of_people',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
