# Generated by Django 4.1 on 2022-08-10 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_reservationform_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=70)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='date',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid date', regex='^(\\d{1,2})([-: .]\\d{1,2})?(-\\d{4})?$')]),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='mail',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Invalid mail', regex='^[^-|_]\\w*[-{0,1}]?\\w*?[@]?\\w*(.com)?$')]),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='number_of_people',
            field=models.SmallIntegerField(validators=[django.core.validators.RegexValidator(message='Invalid time', regex='^[1-5][1-9]?$')]),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone', regex='^[+]?\\d{8,14}$')]),
        ),
        migrations.AlterField(
            model_name='reservationform',
            name='time',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid time', regex='^(\\d{1,2})([-: ]\\d{1,2})?$')]),
        ),
    ]
